Remove unnecessary Autowired from Constructors
conductor-oss/conductor pull request #36
Opened 2024-01-08 22:41 UTC by tiffanyfay

Pull Request type
----

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes (Please run `./gradlew generateLock saveLock` to refresh dependencies)
- [ ] WHOSUSING.md
- [ ] Other (please describe):

Changes in this PR
----
Removed Autowired import/bean
This doesn't change the code behavior/functionality. It's just cleanup.

_Describe the new behavior from this PR, and why it's needed_
Issue # N/A

Alternatives considered
N/A
----

_Describe alternative implementation you have considered_

2024-01-09 19:29 UTC, c4lm requested changes
This is a good idea. Could you please make it so that full build completes successfully?
Not possible to just remove `@Autowired` from property classes

2024-01-10 18:58 UTC, c4lm commented
> @c4lm Thanks for reviewing and the feedback! I hope I addressed it as intended and added them back to property classes, otherwise more feedback would be appreciated!
> 
> In the property class, why is this treated differently? Thanks.
> 
> (Also, builds aren't currently working correctly in my machine right now which is why I didn't know it would fail in advance.)

For `@Component`, `@Service`, and the like, explicit `@Bean`s which don't require additional set up to show up in the context (like `@EnableConfigurationScan` etc.), as long as there's only one constructor, `@Autowired` should have no meaning and should be safe to remove.
But as for `@ConfigurationProperties` classes - they are usually supposed to be populated via field injection, not a constructor. So  I think in our case Spring simply does not pick that constructor unless we mark it as `@Autowired`.
I think that the most proper way would be to get rid of that dependency and make RedisProperties and ConductorProperties entirely separate, of course.

2024-01-10 19:00 UTC, c4lm approved these changes

2024-01-12 18:39 UTC, tiffanyfay commented
@c4lm Ahh ok. Thanks for the detailed explanation!

2024-01-30 22:58 UTC, v1r3n approved these changes

2024-01-30 22:58 UTC, merged